# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-18 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('tuning', models.CharField(max_length=2)),
                ('starting_note', models.CharField(max_length=2)),
                ('ending_note', models.CharField(max_length=2)),
                ('starting_fifth', models.CharField(max_length=2)),
                ('actual_tuning', models.CharField(max_length=2)),
                ('active', models.BooleanField()),
            ],
        ),
    ]
